###########################################################
#Compare Summer12 Vs Phase1 Age0 High Pileup : Real Photons
###########################################################
 
root -l -b -q  CMSAna/ObjectStudies/Photons/ComparePhotonDistributions.C+'("/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtuple.Summer12.HHtoBBGG-14tev-START53_V7A.root","/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtuple.Phase1Age0.WZHgg-125-STAR17_61_V1A.root","Summer12VsPhase1Age0_Real_BarrelPt20To40","Summer12","Phase1-Age0",0)'
root -l -b -q  CMSAna/ObjectStudies/Photons/ComparePhotonDistributions.C+'("/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtuple.Summer12.HHtoBBGG-14tev-START53_V7A.root","/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtuple.Phase1Age0.WZHgg-125-STAR17_61_V1A.root","Summer12VsPhase1Age0_Real_BarrelPt40To60","Summer12","Phase1-Age0",1)'
root -l -b -q  CMSAna/ObjectStudies/Photons/ComparePhotonDistributions.C+'("/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtuple.Summer12.HHtoBBGG-14tev-START53_V7A.root","/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtuple.Phase1Age0.WZHgg-125-STAR17_61_V1A.root","Summer12VsPhase1Age0_Real_BarrelPt60ToInf","Summer12","Phase1-Age0",2)'

root -l -b -q  CMSAna/ObjectStudies/Photons/ComparePhotonDistributions.C+'("/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtuple.Summer12.HHtoBBGG-14tev-START53_V7A.root","/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtuple.Phase1Age0.WZHgg-125-STAR17_61_V1A.root","Summer12VsPhase1Age0_Real_EndcapPt20To40","Summer12","Phase1-Age0",10)'
root -l -b -q  CMSAna/ObjectStudies/Photons/ComparePhotonDistributions.C+'("/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtuple.Summer12.HHtoBBGG-14tev-START53_V7A.root","/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtuple.Phase1Age0.WZHgg-125-STAR17_61_V1A.root","Summer12VsPhase1Age0_Real_EndcapPt40To60","Summer12","Phase1-Age0",11)'
root -l -b -q  CMSAna/ObjectStudies/Photons/ComparePhotonDistributions.C+'("/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtuple.Summer12.HHtoBBGG-14tev-START53_V7A.root","/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtuple.Phase1Age0.WZHgg-125-STAR17_61_V1A.root","Summer12VsPhase1Age0_Real_EndcapPt60ToInf","Summer12","Phase1-Age0",12)'


##############################################################
#Compare Summer12 Vs Phase1 Age0 High Pileup : Fakes Photons
##############################################################

root -l -b -q  CMSAna/ObjectStudies/Photons/ComparePhotonDistributions.C+'("/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtupleFake.Summer12.qcd_pt80To120-START53_V7A.root","/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtupleFake.Phase1Age0.ttHbb-125_STAR17_61_V1A.root","Summer12VsPhase1Age0_Fake_BarrelPt20To40","Summer12","Phase1-Age0",0)'
root -l -b -q  CMSAna/ObjectStudies/Photons/ComparePhotonDistributions.C+'("/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtupleFake.Summer12.qcd_pt80To120-START53_V7A.root","/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtupleFake.Phase1Age0.ttHbb-125_STAR17_61_V1A.root","Summer12VsPhase1Age0_Fake_BarrelPt40To60","Summer12","Phase1-Age0",1)'
root -l -b -q  CMSAna/ObjectStudies/Photons/ComparePhotonDistributions.C+'("/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtupleFake.Summer12.qcd_pt80To120-START53_V7A.root","/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtupleFake.Phase1Age0.ttHbb-125_STAR17_61_V1A.root","Summer12VsPhase1Age0_Fake_BarrelPt60ToInf","Summer12","Phase1-Age0",2)'

root -l -b -q  CMSAna/ObjectStudies/Photons/ComparePhotonDistributions.C+'("/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtupleFake.Summer12.qcd_pt80To120-START53_V7A.root","/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtupleFake.Phase1Age0.ttHbb-125_STAR17_61_V1A.root","Summer12VsPhase1Age0_Fake_EndcapPt20To40","Summer12","Phase1-Age0",10)'
root -l -b -q  CMSAna/ObjectStudies/Photons/ComparePhotonDistributions.C+'("/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtupleFake.Summer12.qcd_pt80To120-START53_V7A.root","/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtupleFake.Phase1Age0.ttHbb-125_STAR17_61_V1A.root","Summer12VsPhase1Age0_Fake_EndcapPt40To60","Summer12","Phase1-Age0",11)'
root -l -b -q  CMSAna/ObjectStudies/Photons/ComparePhotonDistributions.C+'("/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtupleFake.Summer12.qcd_pt80To120-START53_V7A.root","/afs/cern.ch/work/s/sixie/public/Phase2Upgrade/PhotonStudies/ntuples/PhotonNtupleFake.Phase1Age0.ttHbb-125_STAR17_61_V1A.root","Summer12VsPhase1Age0_Fake_EndcapPt60ToInf","Summer12","Phase1-Age0",12)'
  
