import FWCore.ParameterSet.Config as cms

myPATNtupler = cms.EDAnalyzer('PATNtupler',
                              outputFile = cms.string('BACONNtuple.root'),
                              GenParticlesSrcName = cms.string('prunedGen'),
                              GenJetsSrcName = cms.string('ak5GenJets'),
                              PrimaryVerticesSrcName = cms.string('offlinePrimaryVertices'),
                              PrimaryVerticesBSSrcName = cms.string('offlinePrimaryVerticesWithBS'),
                              MuonsSrcName = cms.string('muons'),
                              ElectronsSrcName = cms.string('gsfElectrons'),
                              PhotonsSrcName = cms.string('photons'),
                              PFJetsSrcName = cms.string('ak5PFJets'),
                              PFCandidatesSrcName = cms.string('particleFlow'),
                              debugLevel = cms.int32(0),
                              UseGen = cms.bool(True),
                              PrintDebug = cms.bool(True),
                              FillEGRegressionVars = cms.bool(False),

                              GenJetPtMin = cms.double(0.0),
                              ElePtMin = cms.double(5.0),
                              ElePtMax =  cms.double(99999999),
                              EleEtaMin = cms.double(-3.0),
                              EleEtaMax = cms.double(3.0),
                              MuonPtMin = cms.double(3.0),
                              MuonPtMax = cms.double(99999999),
                              MuonEtaMin = cms.double(-3.0),
                              MuonEtaMax = cms.double(3.0),
                              JetPtMin = cms.double(7.0),
                              PhotonPtMin = cms.double(5.0),
                              )
